import ij.IJ;
import ij.ImagePlus;
import ij.gui.ImageCanvas;
import ij.plugin.PlugIn;
import ij.plugin.frame.RoiManager;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;

/**
 * Main class of the plugin, takes in an import and export file. Underscore required for ImageJ2 plugin convention.
 */
public class File_Uploader implements PlugIn {

    CoordinateController coordControl;

    private JButton importFile;

    private final JFileChooser imported;

    private JPanel panel;

    private JButton exportFile;

    private JLabel importText;

    private JLabel exportText;

    private JLabel log;

    private final JFileChooser exported;

    public File_Uploader() {
        ImagePlus img = IJ.getImage();

        imported = new JFileChooser();
        exported = new JFileChooser();

        coordControl = new CoordinateController(img);

        importFile.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openForImport();
            }
        });

        exportFile.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openForExport();
            }
        });

        ImagePlus imp = IJ.getImage();

        ImageCanvas canvas = imp.getWindow().getCanvas();
        canvas.setFocusable(true);
        PointSwapListener p = new PointSwapListener(log);
        PointDragListener pd = new PointDragListener(log);
        if (canvas.getMouseListeners().length <= 1)
            canvas.addMouseListener(p);
        if (canvas.getMouseListeners().length <= 2)
            canvas.addMouseListener(pd);
        if (canvas.getKeyListeners().length <= 1)
            canvas.addKeyListener(p);

        importFile.setFocusable(false);
        exportFile.setFocusable(false);
        panel.setFocusable(true); //sets focus to the log panel itself
        panel.requestFocusInWindow();

        panel.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_Q && ((e.getModifiersEx() & InputEvent.CTRL_DOWN_MASK) != 0)
                        && ((e.getModifiersEx() & InputEvent.SHIFT_DOWN_MASK) != 0)) {
                    openForExport(); //ctrl + shift + Q to open export
                } else if (e.getKeyCode() == KeyEvent.VK_Q && ((e.getModifiersEx() & InputEvent.CTRL_DOWN_MASK) != 0)) {
                    openForImport(); //ctrl + Q to open import
                }
            }
        });
    }

    public void openForImport() {
        log.setText("Log: Importing...");
        imported.setCurrentDirectory(new File(System.getProperty("user.home")));
        imported.setFileFilter(new FileNameExtensionFilter("JSON files", "json"));
        int returnValue = imported.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = imported.getSelectedFile();
            String filePath = file.getAbsolutePath();
            coordControl.importCoords(filePath);
            importText.setText("Imported: " + filePath);
        }
    }

    public void openForExport() {
        log.setText("Log: Exporting...");
        exported.setCurrentDirectory(new File(System.getProperty("user.home")));
        exported.setFileFilter(new FileNameExtensionFilter("JSON files", "json"));
        int returnValue = exported.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = exported.getSelectedFile();
            String filePath = file.getAbsolutePath();
            try {
                coordControl.exportCoords(filePath);
                exportText.setText("Exported: " + filePath);
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
        }
    }

    public void run(String arg) {
        JFrame frame = new JFrame("FileUploader");

        frame.setContentPane(new File_Uploader().panel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack(); //sizes the window
        frame.setVisible(true);
    }

    public static void main(String[] args) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        importFile = new JButton();
        importFile.setText("Import");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        panel.add(importFile, gbc);
        exportFile = new JButton();
        exportFile.setText("Export");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        panel.add(exportFile, gbc);
        importText = new JLabel();
        importText.setText("Imported: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(importText, gbc);
        exportText = new JLabel();
        exportText.setText("Exported: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(exportText, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        panel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        panel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 40;
        panel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 40;
        panel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 20;
        panel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 20;
        panel.add(spacer6, gbc);
        log = new JLabel();
        log.setText("Log: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(log, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 20;
        panel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 40;
        panel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        panel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        panel.add(spacer10, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
